#
#        _       _       __  __
#       | | ___ (_)_ __ |  \/  | ___  ___ ___  __ _  __ _  ___
#    _  | |/ _ \| | '_ \| |\/| |/ _ \/ __/ __|/ _` |/ _` |/ _ \
#   | |_| | (_) | | | | | |  | |  __/\__ \__ \ (_| | (_| |  __/
#    \___/ \___/|_|_| |_|_|  |_|\___||___/___/\__,_|\__, |\___|
#                                                   |___/
#
#                   Developed by sk_Manux
#

lobbies:
  - "lobby"

msg:
  - "&6&m----------&e&m-------------------------&6&m----------"
  - "  &eBenvenuto su &6&lNupped&e, &6sk_Manux&e."
  - "    &7* &6Forum: &enupped.it"
  - "    &7* &6Store: &estore.nupped.it"
  - "    &7* &6Discord: &eds.nupped.it"
  - "    &7* &6Telegram: &etg.nupped.it"
  - "&6&m----------&e&m-------------------------&6&m----------"